### ISSUE TITLE
3.0.0 upgrade help

### ISSUE THREAD

**Issue by Lokray** [MatthewHerbst/react-to-print#742]
Hi after updateing to 3.0.0 I get the error "t is not a function", even after breaking it down to your example:
<div>
    <button onClick={handlePrint}>Print</button>
    <div ref={contentRef}>Content to print</div>
  </div>

I used chrome on windows.
Please forgive me if this is the wrong place or I am missing info, it's the first time for posting an issue ;)

**Comment by MariusMez** [comment]
Hi, same error on my side after upgrade to v3 :

Before: 	

```ts
const ficheToPrintRef = useRef(null);
const handlePrint = useReactToPrint({
    content: () => ficheToPrintRef.current,
});
```

After my comprehension of the changelog:

```ts
const ficheToPrintRef = useRef<HTMLDivElement>(null);
const handlePrint = useReactToPrint({ contentRef: ficheToPrintRef });
```

But when calling handlePrint I have this error too: `"react-to-print.js?v=05cacf31:163 Uncaught TypeError: t3 is not a function"` and also a warning log on the console : 
```js
"[
    "\"react-to-print\" received a `contentRef` option and a optional-content param passed to its callback. The `contentRef` option will be ignored."
]"
```

edit : lines where the error pop:

```js
function g(e2) {
        const { contentRef: t2, fonts: o2, ignoreGlobalStyles: n2, onBeforePrint: r2, onPrintError: c2, preserveAfterPrint: d2, suppressErrors: u2 } = e2, p2 = (0, s.useCallback)((s2) => {
          l(d2, true);
          const p3 = function({ contentRef: e3, optionalContent: t3, suppressErrors: o3 }) {
            return t3 ? (e3 && i({ level: "warning", messages: ['"react-to-print" received a `contentRef` option and a optional-content param passed to its callback. The `contentRef` option will be ignored.'] }), t3()) : e3 ? e3.current : void i({ messages: ['"react-to-print" did not receive a `contentRef` option or a optional-content param pass to its callback.'], suppressErrors: o3 });
          }({ contentRef: t2, optionalContent: s2, suppressErrors: u2 });
          if (!p3) return void i({ messages: ["There is nothing to print"], suppressErrors: u2 });
          if (!p3) return void i({ messages: ['"react-to-print" could not locate the DOM node corresponding with the `content` prop'], suppressErrors: u2 });
          const g2 = p3.cloneNode(true), f = document.querySelectorAll("link[rel~='stylesheet'], link[as='style']"), m = g2.querySelectorAll("img"), b = g2.querySelectorAll("video"), y = o2 ? o2.length : 0, v = (n2 ? 0 : f.length) + m.length + b.length + y, w = [], E = [], T = function() {
            const e3 = document.createElement("iframe");
            return e3.width = `${document.documentElement.clientWidth}px`, e3.height = `${document.documentElement.clientHeight}px`, e3.style.position = "absolute", e3.style.top = `-${document.documentElement.clientHeight + 100}px`, e3.style.left = `-${document.documentElement.clientWidth + 100}px`, e3.id = "printWindow", e3.srcdoc = "<!DOCTYPE html>", e3;
          }(), A = (t3, o3) => {
            w.includes(t3) ? i({ level: "debug", messages: ["Tried to mark a resource that has already been handled", t3], suppressErrors: u2 }) : (o3 ? (i({ messages: ['"react-to-print" was unable to load a resource but will continue attempting to print the page', ...o3], suppressErrors: u2 }), E.push(t3)) : w.push(t3), w.length + E.length === v && a(T, e2));
          }, x = { contentNode: p3, clonedContentNode: g2, clonedImgNodes: m, clonedVideoNodes: b, numResourcesToLoad: v, originalCanvasNodes: p3.querySelectorAll("canvas") };
          r2 ? r2().then(() => h(T, A, x, e2)).catch((e3) => {
            null == c2 || c2("onBeforePrint", e3);
          }) : h(T, A, x, e2);
        }, [e2]);
        return p2;
      }
```

**Comment by MariusMez** [comment]
Finally problem solved after seeing this issue : https://github.com/MatthewHerbst/react-to-print/issues/724

My previous code was calling handlePrint directly: `onClick={handlePrint}` and now it works only with `onClick={() => handlePrint()}`

**Comment by Lokray** [comment]
Thanks! My research didn't leed to this. But this leeds to a next question, I can't find how the documentTitle is now set. 
Previously i set it like

```tsx
    const handlePrint = useReactToPrint({
        documentTitle: 'Title',
        content: () => componentRef.current,

    });
```
But if I am passing the ref like that, the console says nothing to print

**Comment by MariusMez** [comment]
Try:

```tsx
const handlePrint = useReactToPrint({
        documentTitle: 'Title',
        contentRef: componentRef,
    });
```

**Comment by MatthewHerbst** [comment]
Hey folks, thanks for the messages, apologies if the upgrade process hasn't been smooth. Please feel free to continue posting in this thread and I'll answer/help as best I can. The core change as seen above is a new pattern for passing in the `componentRef` which allows us to be React 19 compatible

**Comment by Idnan** [comment]
Hi guys, I am still getting the same error after upgrading to v3. I tried all the above solutions but none worked. Here's how my code looks like after update.

```tsx
import { Box, Flex, HStack } from '@chakra-ui/react';
import { BaseButton } from '@components/base/base-button';
import { useRef } from 'react';
import { useReactToPrint } from 'react-to-print';
import { TrayListTablePrint } from './tray-list-table-print';

interface TableActionProps {
  onPrint?: () => void;
}

function TableActions({ onPrint }: TableActionProps) {
  return (
    <Flex direction='column'>
      <Flex justifyContent='flex-end' mb={4}>
        <HStack spacing='sm'>
          <BaseButton size='sm' onClick={onPrint} colorScheme='green'>
            Print
          </BaseButton>
        </HStack>
      </Flex>
    </Flex>
  );
}

export function TrayListTable() {
  const componentToPrintRef = useRef(null);

  const handlePrint = useReactToPrint({
    contentRef: componentToPrintRef
  });

  return (
    <Box minH='100%' pos='relative'>
      <TableActions
        onPrint={handlePrint}
      />
      <Box style={{ display: 'none' }}>
        <TrayListTablePrint ref={componentToPrintRef} />
      </Box>
    </Box>
  );
}

```

**Comment by MatthewHerbst** [comment]
@Idnan could you please be more specific about the error you are seeing?

**Comment by Idnan** [comment]
I am getting this error `TypeError: t is not a function` and I am using nextjs v14.2.13 with typescript v5.6.2.

<img width="998" alt="image" src="https://github.com/user-attachments/assets/77b0e193-2f92-4194-a597-9757daf5b923">



Here's how the old code looked like

```tsx
const componentToPrintRef = useRef(null);

const reactToPrintContent = useCallback(() => {
  return componentToPrintRef.current;
}, [componentToPrintRef.current]);

const handlePrint = useReactToPrint({
  content: reactToPrintContent
});
```

And after upgrading the `react-to-print` to v3. I modified the above code to this, and started seeing the above error.

```tsx
const componentToPrintRef = useRef(null);

const handlePrint = useReactToPrint({
  contentRef: componentToPrintRef
});
```

**Comment by MatthewHerbst** [comment]
I see the source of confusion, I will push a doc update right now. @Idnan changing `onPrint={handlePrint}` to `onPrint={() => handlePrint()}` should fix your issue

**Comment by Idnan** [comment]
Thanks @MatthewHerbst for the quick help. I just tried and now it's giving me a new error
```tsx
TypeError: p.cloneNode is not a function
```

**Comment by MatthewHerbst** [comment]
I've published `v3.0.1` which should resolve the `t is not a function` issue. I expect that this primarily impacts non-TypeScript users, since folks using TypeScript will see a type error if they try to pass the print fn directly in v3

@Idnan the `cloneNode is not a function` error is interesting. Could you please share what browser you're using? [`cloneNode`](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) should be supported by all major browsers

**Comment by Idnan** [comment]
Thanks I will upgrade the package to v3.0.1 and test it. 

Regarding the `cloneNode` I am using chrome `129.0` which is the latest version.

**Comment by Idnan** [comment]
I have figured out the issue with the `cloneNode`.

Here's the old code.
```tsx
<Box style={{ display: 'none' }}>
  <TrayListTablePrint ref={componentToPrintRef} columns={columnsToPrint} data={list} />
</Box>
```

I think the issue was with the `ref`. So I wrapped my component  `TrayListTablePrint` in a `div` and assigned the ref to it. And it fixed the issue.
Here's how the new code looks like
```tsx
<Box style={{ display: 'none' }}>
  <div ref={componentToPrintRef}>
    <TrayListTablePrint columns={columnsToPrint} data={list} />
  </div>
</Box>
```

Thanks for the help @MatthewHerbst

**Comment by MatthewHerbst** [comment]
Glad you got it figured out! If your component is a functional component you'll need to wrap it in [`forwardRef`](https://react.dev/reference/react/forwardRef) which should remove the need for the wrapping `div`

**Comment by hemm1** [comment]
Hi! We tried to update to the latest version today and ran into an issue. Earlier, we used `onBeforeGetContent` and a combination of two different refs to be able to load some data and wait for everything to load and render completely before we actually initiated the printing. You helped me a bit with the setup here: https://github.com/MatthewHerbst/react-to-print/issues/469

Now, we are trying to use `onBeforePrint` and `contentRef` to accomplish the same. Our `contentRef` is `null` when we initially start the printing, but `onBeforePrint` is responsible for starting the data fetching and rendering and eventually setting the `contentRef` to the actual node we want to print.

We ran into two issues: 

1. If `contentRef` is `null` when `handlePrint` is first called, the function returns with an error 'There is nothing to print' before even calling the `onBeforePrint` method. This was not the case in the earlier version.
2. To get around this problem, we tried adding a different, placeholder component as the `contentRef` in order to make the `onBeforePrint` run, but we could not get the timing right for the `contentRef` to actually be updated when the element was printed. We had to try twice for each print in order to make it work.

I understand that our setup is a bit special, but it worked like a charm in the previous version. Any pointers at all for how to make it work in version 3 would be greatly appreciated. I can also, of course, post some code or make a separate issue if that is better.

**Comment by MatthewHerbst** [comment]
Hey @hemm1 nice to hear from you again! I believe you should be able to solve your workflow by using the lazy print option we [added](https://github.com/MatthewHerbst/react-to-print/issues/652) in v2.15.0. Basically, you can now delay calling the callback from `useReactToPrint` until you have the content ready. The [`LazyContent`](https://github.com/MatthewHerbst/react-to-print/blob/master/examples/LazyContent/index.tsx) example should point you in the right direction. Please let me know if that doesn't work for you, or if you have trouble adopting it.

**Comment by hemm1** [comment]
Thank you very much! This looks to be right up our alley. Most likely we should have been using Lazy print already, but we did not now it was added until now 😇 We will definitely try it out and get back to you 👌

**Comment by hemm1** [comment]
Hi again! Me and my colleague tinkered a bit with this today, and we could not get the LazyContent to work for us either, unfortunately. The problem was the same, in that the `contentRef` is `null` when `handlePrint` is called. So the `onBeforePrint` function never gets called.

Our problem is that the component we want to print does not exist (nor the data for it) when we click the button to print it. When we click the print button, we then first want to do a couple data calls, render the component and then finally print the component.

We did manage to find a way to do it which seems to work perfectly, however. Instead of invoking `react-to-print` at the beginning of the process and then needing `react-to-print` to orchestrate everything and wait for the process to finish, we tried to make the component render without involving `react-to-print` and then actually invoking `handlePrint` when everything is ready to be printed. This removes the need for the "manual" Promise resolving and indeed any refs other than one `useCallback` and actually makes the code easier in our case.

A quick code example is in order:

```tsx
const [isPrinting, setIsPrinting] = useState(false);

const handlePrint = useReactToPrint({
  onAfterPrint: () => setIsPrinting(false),
});

const callbackRef = useCallback(
  (node: HTMLDivElement) => {
    if (node !== null) handlePrint(() => node);
  },
  [handlePrint]
);

return (
  <div className={c.link} onClick={() => setIsPrinting(true)}>
    <div style={{ display: 'none' }}>
      {isPrinting && (
        <React.Suspense fallback={null}>
          <PrintablePriceBoard id={car.id} salesForm={car.salesForm} ref={callbackRef} />
        </React.Suspense>
      )}
    </div>
  </div>
```

Inside the `PrintablePriceBoard` component we trigger data fetching and wait until all data is fetched before we render anything. And the containing `div` of the component gets passed the `ref` in the normal way like so : `<div ref={ref}>`.

We can't see any problems with this and are very happy with how it all turned out. 🎉

Thank you again for an awesome library and very attentive and helpful comments! 🙌

**Comment by MatthewHerbst** [comment]
@hemm1 that looks great, thank you so much for sharing, callback ref makes perfect sense! I'll look into how to best update the README and examples to show this method

**Comment by eugene-khyst** [comment]
Based on @hemm1 answer I came up with the following generic component `PrintableImages` that prints lazy loaded images:

```tsx
interface Props {
  images: () => Promise<Blob[]>;
  printing: boolean;
  setPrinting: React.Dispatch<React.SetStateAction<boolean>>;
}

export const PrintableImages: React.FC<Props> = ({images, printing, setPrinting}: Props) => {
  const [printImagesUrls, setPrintImagesUrls] = useState<string[]>([]);

  const printFn = useReactToPrint({
    onAfterPrint: () => {
      setPrintImagesUrls(prev => {
        prev.forEach((url: string) => {
          URL.revokeObjectURL(url);
        });
        return [];
      });
      setPrinting(false);
    },
  });

  const printRef = useCallback(
    (node: HTMLDivElement | null) => {
      if (node) {
        printFn(() => node);
      }
    },
    [printFn]
  );

  useEffect(() => {
    if (!printing) {
      return;
    }
    void (async () => {
      const urls: string[] = (await images).map((blob: Blob): string => URL.createObjectURL(blob));
      setPrintImagesUrls(urls);
    })();
  }, [image, printing]);

  return (
    <div style={{display: 'none'}}>
      {!!printImagesUrls.length && (
        <div ref={printRef}>
          {printImagesUrls.map((url: string, i: number) => (
            <img key={i} src={url} style={{breakAfter: 'always'}} />
          ))}
        </div>
      )}
    </div>
  );
};
```

Example usage:

```tsx
const [isPrinting, setIsPrinting] = useState<boolean>(false);
//...
<Button onClick={() => {setIsPrinting(true)}}>Print</Button>
<PrintableImages image={images} printing={isPrinting} setPrinting={setIsPrinting} />
```

**Comment by gyanranjan89** [comment]
I am unable to print, I using below code: I am getting "There is nothing to Print" error. Please suggest.
```jsx
function FormPrintWrapper(props) {
	const parsed = Utility.parseQueryString(window.location.search);

	let {engagementId, documentId, snapshotId, snapshotUser, snapshotDate} = props;
	const isAutomatedPrint = parsed.isautomatedprint;

	// The component was called from outside Kronos (ie: batch print). Get the parameters from the URL
	if (isAutomatedPrint) {
		engagementId = parsed.engagementid;
		documentId = parsed.documentid;
		snapshotId = parsed.snapshotid;
		snapshotUser = parsed.snapshotuser;
		snapshotDate = parsed.snapshotdate?.toUpperCase();
	}

	if (snapshotId === '-1') {
		snapshotDate = moment().format('YYYY-MM-DDTHH:mm:ss');
	}

	const printViewRef = useRef(null);
	const componentRef = useRef(null);

	const [isRendered, setIsRendered] = useState(false);

	const handlePrint = useReactToPrint({
		contentRef: printViewRef.current
	});

	useEffect(() => {
		if (isRendered) {
			setTimeout(() => {
				handlePrint();
			}, 500);
		}
	}, [isRendered]);

	function renderPrintViewContent() {
		return (
			<FormPrintViewContainer
				setIsRendered={setIsRendered}
				engagementId={engagementId}
				documentId={documentId}
				snapshotId={snapshotId}
				snapshotUser={snapshotUser}
				snapshotDate={snapshotDate}
			/>
		);
	}

	if (!isRendered) {
		printViewRef.current = renderPrintViewContent();
	}

	return (
		<StyledFormPrintWrapper ref={componentRef} className="StyledFormPrintWrapper">
			{printViewRef.current}
		</StyledFormPrintWrapper>
	);
}

export default FormPrintWrapper;
```

**Comment by MatthewHerbst** [comment]
@gyanranjan89 pass the whole ref to `react-to-print`, not just the `.content`:

```jsx
// Before
const handlePrint = useReactToPrint({
  contentRef: printViewRef.current
});

// After
const handlePrint = useReactToPrint({
  contentRef: printViewRef
});
```

Your setup could also be significantly simplified if `FormPrintViewContainer` could take a ref:

```jsx
return (
  <StyledFormPrintWrapper ref={componentRef} className="StyledFormPrintWrapper">
    <FormPrintViewContainer
      setIsRendered={setIsRendered}
      engagementId={engagementId}
      documentId={documentId}
      ref={printViewRef}
      snapshotId={snapshotId}
      snapshotUser={snapshotUser}
      snapshotDate={snapshotDate}
    />
  </StyledFormPrintWrapper>
);
```

**Comment by gyanranjan89** [comment]
> ```ts
> ficheToPrintRef
> ```

I made the changes are required but now I am getting below error:

<img width="325" alt="image" src="https://github.com/user-attachments/assets/36104486-4a9d-4408-805f-c82f52b7b32f">

**Comment by MatthewHerbst** [comment]
You'll need to share some code please. Ideally if you could make a working [codesandbox](https://codesandbox.io/s/rzdhd), that would be best

**Comment by gyanranjan89** [comment]
> You'll need to share some code please. Ideally if you could make a working [codesandbox](https://codesandbox.io/s/rzdhd), that would be best

This is mostly what I am trying to do: (I have to show the data on underlying page and also print)

https://codesandbox.io/p/sandbox/new-bash-d9vrfq?file=%2Fexamples%2FCustomPrint%2Findex.js%3A15%2C10&workspaceId=43036a6b-06af-4925-bfb0-ba5780f8aa7a

**Comment by MatthewHerbst** [comment]
The way you have it right now, the ref value is the React component, not the underlying DOM node. Here is a modified version of your code working: https://codesandbox.io/p/sandbox/keen-meadow-tdzgkr?file=%2Fexamples%2FCustomPrint%2Findex.js%3A15%2C21

Notice that I used css to manage the print content displaying or not. There are other ways to do this with state and javascript, but the css option is by far the simplest. If you want the print content (data in your case) to always display, just remove the css class I added

**Comment by gyanranjan89** [comment]
> The way you have it right now, the ref value is the React component, not the underlying DOM node. Here is a modified version of your code working: https://codesandbox.io/p/sandbox/keen-meadow-tdzgkr?file=%2Fexamples%2FCustomPrint%2Findex.js%3A15%2C21
> 
> Notice that I used css to manage the print content displaying or not. There are other ways to do this with state and javascript, but the css option is by far the simplest. If you want the print content (data in your case) to always display, just remove the css class I added

Thank you so much, making that change just worked. Earlier we had setup like that to print with previous version.

**Comment by markwillcraft** [comment]
Can you help me? I'm also experiencing the "['"react-to-print" did not receive a `contentRef` op…or a optional-content param pass to its callback.']"

```jsx
import { useRef, useState } from "react";
import { useReactToPrint } from "react-to-print";
import InvoiceTablePrintPage from "./InvoiceTablePrintPage";
import { ActionIcon, Table, Checkbox } from "@mantine/core";
import { IconPrinter } from "@tabler/icons-react";

const PaidTable = ({ items }) => {
  const [selection, setSelection] = useState([]);
  const [printInvoice, setPrintInvoice] = useState({ show: false, invoice: null });
  const printRef = useRef(null);

  const handlePrint = useReactToPrint({
    content: () => printRef.current || null,
    onAfterPrint: () => setPrintInvoice({ show: false, invoice: null }),
  });

  const onPrint = (invoice) => {
    setPrintInvoice({ show: true, invoice });
    setTimeout(() => handlePrint(), 0);
  };

  return (
    <>
      <Table>
        <Table.Tbody>
          {items.map((item) => (
            <Table.Tr key={item._id}>
              <Table.Td>
                <Checkbox checked={selection.includes(item._id)} onChange={() => toggleRow(item._id)} />
              </Table.Td>
              <Table.Td>{item.invoiceNumber}</Table.Td>
              <Table.Td>{item.totalCost}</Table.Td>
              <Table.Td>
                <ActionIcon size="lg" color="gray" onClick={() => onPrint(item)}>
                  <IconPrinter size={18} />
                </ActionIcon>
              </Table.Td>
            </Table.Tr>
          ))}
        </Table.Tbody>
      </Table>
      
      {printInvoice.show && (
        <div style={{ display: "none" }}>
          <InvoiceTablePrintPage ref={printRef} invoice={printInvoice.invoice} />
        </div>
      )}
    </>
  );
};

export default PaidTable;

```

```jsx
import React, { Fragment, forwardRef } from "react";
import { Box, Text, Card, Divider } from "@mantine/core";
import { Invoice, SERVICE_INSTANCE_TYPE } from "@/types";
import "./invoice.css";
import moment from "moment";
import PartTable from "../[id]/invoices/_components/PartTable";
import LaborTable from "../[id]/invoices/_components/LaborTable";
import OtherChargesTable from "../[id]/invoices/_components/OtherChargesTable";

interface InvoiceTableProps {
  invoice: Invoice;
}

const InvoiceTablePrintPage = forwardRef<HTMLDivElement, InvoiceTableProps>(
  ({ invoice }, ref) => {
    const serviceProviderId = invoice.serviceProvider.id;
    const dealerCustomerId = invoice.dealer.id;

    const laborItems = invoice.lineItems.filter(
      (item) => item.type === SERVICE_INSTANCE_TYPE.LABOR,
    );

    const partItems = invoice.lineItems.filter(
      (item) => item.type === SERVICE_INSTANCE_TYPE.PART,
    );

    const otherItems = invoice.lineItems.filter(
      (item) => item.type === SERVICE_INSTANCE_TYPE.OTHER,
    );

    const laborItemsTotal = laborItems.reduce(
      (acc, item) => acc + item.total,
      0,
    );
    const partItemsTotal = partItems.reduce((acc, item) => acc + item.total, 0);
    const otherItemsTotal = otherItems.reduce(
      (acc, item) => acc + item.total,
      0,
    );

    const subTotal = laborItemsTotal + partItemsTotal + otherItemsTotal;
    const salesTax = subTotal * 0.13;
    const grandTotal = subTotal + salesTax;

    return (
        <div ref={ref} className="printableComponent">
  // content
        </div>
    );
  },
);

InvoiceTablePrintPage.displayName = "InvoiceTablePrintPage";
export default InvoiceTablePrintPage;

```

**Comment by MatthewHerbst** [comment]
@markwillcraft the function property has changed from `content` -> `contentRef`, and the type changed from being a function to just being the ref itself.

```js
// change this
const handlePrint = useReactToPrint({
  content: () => printRef.current || null,
  onAfterPrint: () => setPrintInvoice({ show: false, invoice: null }),
});

// to this
const handlePrint = useReactToPrint({
  contentRef: printRef,
  onAfterPrint: () => setPrintInvoice({ show: false, invoice: null }),
});
```

**Comment by markwillcraft** [comment]
> @markwillcraft the function property has changed from `content` -> `contentRef`, and the type changed from being a function to just being the ref itself.
> 
> ```js
> // change this
> const handlePrint = useReactToPrint({
>   content: () => printRef.current || null,
>   onAfterPrint: () => setPrintInvoice({ show: false, invoice: null }),
> });
> 
> // to this
> const handlePrint = useReactToPrint({
>   contentRef: printRef,
>   onAfterPrint: () => setPrintInvoice({ show: false, invoice: null }),
> });
> ```

Thank you so much, brotha! All goods now. 🙏🏼

**Comment by dardan100** [comment]
```jsx
  const componentRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  }); 
  
  <div className="px-2 min-h-[768px] min-w-[500px] mx-auto"> 
  <div > {/* The div containing your content to print */}
  <button onClick={() => handlePrint()}>Print CV</button>
    <CvMain
      fullName={fullName}
      email={email}
      phone={phone}
      aboutMe={aboutMe}
      education={education}
      skills={skills}
      workExperiences={workExperiences}
    />
     </div>
   </div> 
```
   
When i click the button PRINT CV  its showing me these errors
> "react-to-print" did not receive a `contentRef` op…or a optional-content param pass to its callback.' There is nothing to print'

**Comment by MatthewHerbst** [comment]
@dardan100 similar to the previous post, you need to change `content: () => componentRef.current` -> `contentRef: componentRef`

**Comment by dardan100** [comment]
> @dardan100 similar to the previous post, you need to change `content: () => componentRef.current` -> `contentRef: componentRef`

Now its showing me this slightly different error 
react-to-print" received a `contentRef` option an…allback. The `contentRef` option will be ignored.'
"There is nothing to print"

**Comment by MatthewHerbst** [comment]
@dardan100 in your example in your first post, you never attach the `componentRef` to anything. Is that missing, or did you not show all of your code? For example, a full example of your code might look something like this:

```jsx
  const componentRef = useRef();

  const handlePrint = useReactToPrint({
    contentRef: componentRef
  }); 
  
  <div className="px-2 min-h-[768px] min-w-[500px] mx-auto"> 
    <button onClick={() => handlePrint()}>Print CV</button>
    <div ref={componentRef}> {/* The div containing your content to print */}
      <CvMain
        fullName={fullName}
        email={email}
        phone={phone}
        aboutMe={aboutMe}
        education={education}
        skills={skills}
        workExperiences={workExperiences}
      />
    </div>
  </div> 
```

Notice how I passed the `componentRef` as a `ref` prop to the `div` being printed. I also moved the print button out of the `div` being printed for a nicer experience.

**Comment by dardan100** [comment]
> ```js
>  ref={componentRef}
> ```

Its working  perfectly right now but how are you so smart??? lol thank you so much for the help <3

**Comment by EhsKarimi** [comment]
While hemm1's solution works for showing updated content, it still has issues displaying certain parts of the content component.
For example, if you use react-jsbarcode, it doesn't appear in the printed window, even though it worked in version 2.
I suspect (though I'm not entirely sure) that react-jsbarcode updates and renders after the mounting cycle, and react-to-print v3 might not be capturing the updated state.

**Comment by MatthewHerbst** [comment]
@EhsKarimi `react-to-print` certainly does not know about the individual render states of _any_ of your components. You should track those yourself and only call print when your components have loaded. If you need help with this, please make a Codesandbox showing your issue and I'd be happy to take a look

**Comment by yadi09** [comment]
```jsx
import React, { useRef } from "react";
import { useReactToPrint } from "react-to-print";

const PrintComponent = () => {
    const componentRef = useRef(null);

    const handlePrint = useReactToPrint({
        content: componentRef
    });

    return (
        <div>
            <button onClick={() => handlePrint()}>Print</button>
            <div ref={componentRef}>
                <h1>This is a printable component</h1>
                <p>Only this content will be printed.</p>
            </div>
        </div>
    );
};

```
@MatthewHerbst When i click the button Print its showing me these errors:
![image](https://github.com/user-attachments/assets/1fa3f1e9-163a-4f7e-9e21-11a816a158a1)

**Comment by MatthewHerbst** [comment]
@yadi09 change `content: componentRef` -> `contentRef: componentRef`

**Comment by yadi09** [comment]
> @yadi09 change `content: componentRef` -> `contentRef: componentRef`

it works, thank you

**Comment by joyal007** [comment]
```jsx
const contRef = useRef();
const reactToPrintFn = useReactToPrint({ contentRef: contRef }); 

return (
  <div ref={contRef}>
    <div className="tw-text-red-400">I'm getting printed</div>
    <button onClick={reactToPrintFn}>Print</button>
  </div>
);
```

react-to-print is failing to take tailwind css styling while generating PDF.

UI:
<img width="311" alt="Image" src="https://github.com/user-attachments/assets/ff607eed-f14a-4ba4-b177-cca9ef5ed19f" />
Pdf print generated:

<img width="330" alt="Image" src="https://github.com/user-attachments/assets/5f549c01-cb67-42be-9a3c-2b2ec84ef7c0" />

**Comment by MatthewHerbst** [comment]
@joyal007 could you please make a Codesandbox or similar showing the problem? Hard to debug from images

**Comment by joyal007** [comment]
> [@joyal007](https://github.com/joyal007) could you please make a Codesandbox or similar showing the problem? Hard to debug from images

Hi @MatthewHerbst,  sorry for the late response, i have debugged issue, my tailwind config have a setup 
```css
  important: "#body"
```
This is causing issue in applying style to element inside iframe. I created a ticket, https://github.com/MatthewHerbst/react-to-print/issues/784, to track this. Any possible solution that you can refer in this case?

**Comment by WaleedZ90** [comment]
in v2 i used the `content` to return a custom element that includes a header in the print template.
I did this by cloning the ref element and adding the header to it.

How can I achieve the same thing in v3? is it possible or i will have to create a custom printer template and pass it's ref?

here's my implementation
```typescript
interface PrintComponentProps {
    pageHeader?: string;
    componentRef: React.RefObject<HTMLElement>;
}

const PrintComponent = ({ pageHeader, componentRef }: PrintComponentProps) => {
    const handlePrint = useReactToPrint({
        contentRef: componentRef,
        documentTitle: pageHeader,
        content: () => { // this part here is not possible in v3 anymore
            const element = componentRef.current.cloneNode(true) as HTMLElement;
            createPageStyles(element);

            if (pageHeader) {
                const pageHeaderElement = document.createElement('h1');
                pageHeaderElement.innerText = pageHeader;
                createPageHeaderStyles(pageHeaderElement);

                element.prepend(pageHeaderElement);
            }

            return element;
        },
    });

    return (
        <Button
            data-testid="PrintComponentButton"
            label="Print"
            startIcon={<PrintIcon />}
            color="primary"
            variant="contained"
            onClick={handlePrint}
        />
    );
};
```

**Comment by MatthewHerbst** [comment]
Hi @WaleedZ90. This should be possible using the lazy method of passing content to the function. [Here's](https://github.com/MatthewHerbst/react-to-print/blob/master/examples/LazyContent/index.tsx) a super simple example.

In your code this would look something like:

```tsx
const printFn = useReactToPrint({
    documentTitle: pageHeader
});

const handlePrint = useCallback(() => {
  const element = componentRef.current.cloneNode(true) as HTMLElement;
  createPageStyles(element);

  if (pageHeader) {
      const pageHeaderElement = document.createElement('h1');
      pageHeaderElement.innerText = pageHeader;
      createPageHeaderStyles(pageHeaderElement);

      element.prepend(pageHeaderElement);
  }

  printFn(() => element); 
}, [pageHeader , printFn]);
```

**Comment by WaleedZ90** [comment]
> Hi [@WaleedZ90](https://github.com/WaleedZ90). This should be possible using lazy method of passing content to the function. [Here's](https://github.com/MatthewHerbst/react-to-print/blob/master/examples/LazyContent/index.tsx) a super simple example.
> 
> In your code this would look something like:
> 
> const printFn = useReactToPrint({
>     documentTitle: pageHeader
> });
> 
> const handlePrint = useCallback(() => {
>   const element = componentRef.current.cloneNode(true) as HTMLElement;
>   createPageStyles(element);
> 
>   if (pageHeader) {
>       const pageHeaderElement = document.createElement('h1');
>       pageHeaderElement.innerText = pageHeader;
>       createPageHeaderStyles(pageHeaderElement);
> 
>       element.prepend(pageHeaderElement);
>   }
> 
>   printFn(element); 
> }, [pageHeader , printFn]);

Ah thank youuuuu it worked!

I followed your code suggestions but I had to pass an anonymous function to the printFn to make it work

```typescript
printFn(() => element);
```

**Comment by MatthewHerbst** [comment]
Awesome! Apologies for that mistake, I updated my above comment so others finding it don't get confused. Please let me know if you run into any other issues

**Comment by stevecastaneda** [comment]
React 18 + Vite 6, still getting the "no content" error.  Here's what I have.

```jsx
export function DetailsContainer() {
  const printComponentRef = useRef<HTMLDivElement>(null);

  const handlePrintScheduleClick = useReactToPrint({
    contentRef: printComponentRef,
  });

  return (
    <div>
      <button onClick={() => handlePrintScheduleClick()}>Print</button>
      <div ref={printComponentRef}>Content to print</div>
    </div>
  );
}
```

Error: 

`There is nothing to print because the "content" prop returned "null". Please ensure "content" is renderable before allowing "react-to-print" to be called.`

I will revert to version 2 for now, but I just couldn't get v3 to work.

**Comment by MatthewHerbst** [comment]
> `There is nothing to print because the "content" prop returned "null". Please ensure "content" is renderable before allowing "react-to-print" to be called.`

@stevecastaneda This error does not exist in version 3. It sounds like you were still using version 2 even though you had changed your code to be version 3 based.

**Comment by stevecastaneda** [comment]
@MatthewHerbst You're right, my mistake. 

I do see this warning in the console, and it goes away if I ensure the click is called using an arrow function vs. just passing in the function itself.

```
[
    "\"react-to-print\" received a `contentRef` option and a optional-content param passed to its callback. The `contentRef` option will be ignored."
]
```

Changed `onClick={handleClick}` to `onClick={() => handleClick()}`

**Comment by MatthewHerbst** [comment]
@stevecastaneda glad you got it figured out. Regarding the warning, what version are you using exactly? Version `3.1.0` should have resolved that, though only if the thing being passed to the function is an [`instanceof Event`](https://github.com/MatthewHerbst/react-to-print/pull/803). Otherwise needing to wrap your handler in a function is expected between version `3.0.0` -> `3.0.6`

**Comment by stevecastaneda** [comment]
@MatthewHerbst Confirmed I am on `3.1.0` and am getting that warning with `onClick={handleClick}`

**Comment by MatthewHerbst** [comment]
@stevecastaneda thanks, I'm able to replicate. I'm making a fix here: https://github.com/MatthewHerbst/react-to-print/pull/812

**Comment by MatthewHerbst** [comment]
@stevecastaneda I just published `v3.1.1`, please let me know if it resolves your issue, thanks!

**Comment by stevecastaneda** [comment]
@MatthewHerbst `v3.1.1` fixed the warning with `onClick={handleClick}`, thanks!
